name: ESlint

on:
  push:
      branches:
          - dev
  pull_request:

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install npm dependencies
      run: cd app && npm ci
    - name: Run linter
      run: cd app && npm run lint
